// This file is autogenerated from the corresponding .mdesk file

UI_Box* UI_ParentPeek(UI_Cache* cache) { return *(cache->parent_stack.top-1); }
UI_FontInfo* UI_FontPeek(UI_Cache* cache) { return *(cache->font_stack.top-1); }
u32 UI_BoxColorPeek(UI_Cache* cache) { return *(cache->bg_color_stack.top-1); }
u32 UI_HotColorPeek(UI_Cache* cache) { return *(cache->hot_color_stack.top-1); }
u32 UI_ActiveColorPeek(UI_Cache* cache) { return *(cache->active_color_stack.top-1); }
f32 UI_RoundingPeek(UI_Cache* cache) { return *(cache->rounding_stack.top-1); }
f32 UI_EdgeSoftnessPeek(UI_Cache* cache) { return *(cache->softness_stack.top-1); }
f32 UI_EdgeSizePeek(UI_Cache* cache) { return *(cache->edge_size_stack.top-1); }
u32 UI_EdgeColorPeek(UI_Cache* cache) { return *(cache->edge_color_stack.top-1); }
u32 UI_TextColorPeek(UI_Cache* cache) { return *(cache->text_color_stack.top-1); }
UI_Size UI_PrefWidthPeek(UI_Cache* cache) { return *(cache->pref_width_stack.top-1); }
UI_Size UI_PrefHeightPeek(UI_Cache* cache) { return *(cache->pref_height_stack.top-1); }
axis2 UI_LayoutAxisPeek(UI_Cache* cache) { return *(cache->layout_axis_stack.top-1); }
UI_RenderFunction* UI_CustomRenderFunctionPeek(UI_Cache* cache) { return *(cache->render_function_stack.top-1); }
rect UI_ClippingRectPeek(UI_Cache* cache) { return *(cache->clipping_rect_stack.top-1); }

UI_Box* UI_ParentPush(UI_Cache* cache, UI_Box* parent) { cache->parent_stack.len++; *cache->parent_stack.top=parent; cache->parent_stack.top++; return parent; }
UI_FontInfo* UI_FontPush(UI_Cache* cache, UI_FontInfo* font) { cache->font_stack.len++; *cache->font_stack.top=font; cache->font_stack.top++; return font; }
u32 UI_BoxColorPush(UI_Cache* cache, u32 bg_color) { cache->bg_color_stack.len++; *cache->bg_color_stack.top=bg_color; cache->bg_color_stack.top++; return bg_color; }
u32 UI_HotColorPush(UI_Cache* cache, u32 hot_color) { cache->hot_color_stack.len++; *cache->hot_color_stack.top=hot_color; cache->hot_color_stack.top++; return hot_color; }
u32 UI_ActiveColorPush(UI_Cache* cache, u32 active_color) { cache->active_color_stack.len++; *cache->active_color_stack.top=active_color; cache->active_color_stack.top++; return active_color; }
f32 UI_RoundingPush(UI_Cache* cache, f32 rounding) { cache->rounding_stack.len++; *cache->rounding_stack.top=rounding; cache->rounding_stack.top++; return rounding; }
f32 UI_EdgeSoftnessPush(UI_Cache* cache, f32 softness) { cache->softness_stack.len++; *cache->softness_stack.top=softness; cache->softness_stack.top++; return softness; }
f32 UI_EdgeSizePush(UI_Cache* cache, f32 edge_size) { cache->edge_size_stack.len++; *cache->edge_size_stack.top=edge_size; cache->edge_size_stack.top++; return edge_size; }
u32 UI_EdgeColorPush(UI_Cache* cache, u32 edge_color) { cache->edge_color_stack.len++; *cache->edge_color_stack.top=edge_color; cache->edge_color_stack.top++; return edge_color; }
u32 UI_TextColorPush(UI_Cache* cache, u32 text_color) { cache->text_color_stack.len++; *cache->text_color_stack.top=text_color; cache->text_color_stack.top++; return text_color; }
UI_Size UI_PrefWidthPush(UI_Cache* cache, UI_Size pref_width) { cache->pref_width_stack.len++; *cache->pref_width_stack.top=pref_width; cache->pref_width_stack.top++; return pref_width; }
UI_Size UI_PrefHeightPush(UI_Cache* cache, UI_Size pref_height) { cache->pref_height_stack.len++; *cache->pref_height_stack.top=pref_height; cache->pref_height_stack.top++; return pref_height; }
axis2 UI_LayoutAxisPush(UI_Cache* cache, axis2 layout_axis) { cache->layout_axis_stack.len++; *cache->layout_axis_stack.top=layout_axis; cache->layout_axis_stack.top++; return layout_axis; }
UI_RenderFunction* UI_CustomRenderFunctionPush(UI_Cache* cache, UI_RenderFunction* render_function) { cache->render_function_stack.len++; *cache->render_function_stack.top=render_function; cache->render_function_stack.top++; return render_function; }
rect UI_ClippingRectPush(UI_Cache* cache, rect clipping_rect) { cache->clipping_rect_stack.len++; *cache->clipping_rect_stack.top=clipping_rect; cache->clipping_rect_stack.top++; return clipping_rect; }

UI_Box* UI_ParentSetNext(UI_Cache* cache, UI_Box* parent) { *cache->parent_stack.top=parent; cache->parent_stack.top++; cache->parent_stack.auto_pop=true; return parent; }
UI_FontInfo* UI_FontSetNext(UI_Cache* cache, UI_FontInfo* font) { *cache->font_stack.top=font; cache->font_stack.top++; cache->font_stack.auto_pop=true; return font; }
u32 UI_BoxColorSetNext(UI_Cache* cache, u32 bg_color) { *cache->bg_color_stack.top=bg_color; cache->bg_color_stack.top++; cache->bg_color_stack.auto_pop=true; return bg_color; }
u32 UI_HotColorSetNext(UI_Cache* cache, u32 hot_color) { *cache->hot_color_stack.top=hot_color; cache->hot_color_stack.top++; cache->hot_color_stack.auto_pop=true; return hot_color; }
u32 UI_ActiveColorSetNext(UI_Cache* cache, u32 active_color) { *cache->active_color_stack.top=active_color; cache->active_color_stack.top++; cache->active_color_stack.auto_pop=true; return active_color; }
f32 UI_RoundingSetNext(UI_Cache* cache, f32 rounding) { *cache->rounding_stack.top=rounding; cache->rounding_stack.top++; cache->rounding_stack.auto_pop=true; return rounding; }
f32 UI_EdgeSoftnessSetNext(UI_Cache* cache, f32 softness) { *cache->softness_stack.top=softness; cache->softness_stack.top++; cache->softness_stack.auto_pop=true; return softness; }
f32 UI_EdgeSizeSetNext(UI_Cache* cache, f32 edge_size) { *cache->edge_size_stack.top=edge_size; cache->edge_size_stack.top++; cache->edge_size_stack.auto_pop=true; return edge_size; }
u32 UI_EdgeColorSetNext(UI_Cache* cache, u32 edge_color) { *cache->edge_color_stack.top=edge_color; cache->edge_color_stack.top++; cache->edge_color_stack.auto_pop=true; return edge_color; }
u32 UI_TextColorSetNext(UI_Cache* cache, u32 text_color) { *cache->text_color_stack.top=text_color; cache->text_color_stack.top++; cache->text_color_stack.auto_pop=true; return text_color; }
UI_Size UI_PrefWidthSetNext(UI_Cache* cache, UI_Size pref_width) { *cache->pref_width_stack.top=pref_width; cache->pref_width_stack.top++; cache->pref_width_stack.auto_pop=true; return pref_width; }
UI_Size UI_PrefHeightSetNext(UI_Cache* cache, UI_Size pref_height) { *cache->pref_height_stack.top=pref_height; cache->pref_height_stack.top++; cache->pref_height_stack.auto_pop=true; return pref_height; }
axis2 UI_LayoutAxisSetNext(UI_Cache* cache, axis2 layout_axis) { *cache->layout_axis_stack.top=layout_axis; cache->layout_axis_stack.top++; cache->layout_axis_stack.auto_pop=true; return layout_axis; }
UI_RenderFunction* UI_CustomRenderFunctionSetNext(UI_Cache* cache, UI_RenderFunction* render_function) { *cache->render_function_stack.top=render_function; cache->render_function_stack.top++; cache->render_function_stack.auto_pop=true; return render_function; }
rect UI_ClippingRectSetNext(UI_Cache* cache, rect clipping_rect) { *cache->clipping_rect_stack.top=clipping_rect; cache->clipping_rect_stack.top++; cache->clipping_rect_stack.auto_pop=true; return clipping_rect; }

UI_Box* UI_ParentPop(UI_Cache* cache) { cache->parent_stack.len--; cache->parent_stack.top--; return *cache->parent_stack.top; }
UI_FontInfo* UI_FontPop(UI_Cache* cache) { cache->font_stack.len--; cache->font_stack.top--; return *cache->font_stack.top; }
u32 UI_BoxColorPop(UI_Cache* cache) { cache->bg_color_stack.len--; cache->bg_color_stack.top--; return *cache->bg_color_stack.top; }
u32 UI_HotColorPop(UI_Cache* cache) { cache->hot_color_stack.len--; cache->hot_color_stack.top--; return *cache->hot_color_stack.top; }
u32 UI_ActiveColorPop(UI_Cache* cache) { cache->active_color_stack.len--; cache->active_color_stack.top--; return *cache->active_color_stack.top; }
f32 UI_RoundingPop(UI_Cache* cache) { cache->rounding_stack.len--; cache->rounding_stack.top--; return *cache->rounding_stack.top; }
f32 UI_EdgeSoftnessPop(UI_Cache* cache) { cache->softness_stack.len--; cache->softness_stack.top--; return *cache->softness_stack.top; }
f32 UI_EdgeSizePop(UI_Cache* cache) { cache->edge_size_stack.len--; cache->edge_size_stack.top--; return *cache->edge_size_stack.top; }
u32 UI_EdgeColorPop(UI_Cache* cache) { cache->edge_color_stack.len--; cache->edge_color_stack.top--; return *cache->edge_color_stack.top; }
u32 UI_TextColorPop(UI_Cache* cache) { cache->text_color_stack.len--; cache->text_color_stack.top--; return *cache->text_color_stack.top; }
UI_Size UI_PrefWidthPop(UI_Cache* cache) { cache->pref_width_stack.len--; cache->pref_width_stack.top--; return *cache->pref_width_stack.top; }
UI_Size UI_PrefHeightPop(UI_Cache* cache) { cache->pref_height_stack.len--; cache->pref_height_stack.top--; return *cache->pref_height_stack.top; }
axis2 UI_LayoutAxisPop(UI_Cache* cache) { cache->layout_axis_stack.len--; cache->layout_axis_stack.top--; return *cache->layout_axis_stack.top; }
UI_RenderFunction* UI_CustomRenderFunctionPop(UI_Cache* cache) { cache->render_function_stack.len--; cache->render_function_stack.top--; return *cache->render_function_stack.top; }
rect UI_ClippingRectPop(UI_Cache* cache) { cache->clipping_rect_stack.len--; cache->clipping_rect_stack.top--; return *cache->clipping_rect_stack.top; }

